Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# retrieve world map from GeoPandas
world_map = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))

# Set up world map plot
fig, ax = plt.subplots(figsize=(15, 10))
world_map.plot(color="grey", ax=ax)

# Plot Fireball Locations with Energy
x = fireball_df["longitude"]
y = fireball_df["latitude"]
z = fireball_df["energy"]
plt.scatter(x, y, s=5*z, c=z, cmap="autumn")
plt.colorbar(label="Approximate Total Radiated Energy (10^10 Joules)")

# Setup Axis Limits and Title/Labels
plt.xlim([-180, 180])
plt.ylim([-90, 90])
plt.title("Energy of Fireball Observations")
plt.xlabel("Longitude (Degrees)")
plt.ylabel("Latitude (Degrees)")
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[8], line 2[0m
[1;32m      1[0m [38;5;66;03m# retrieve world map from GeoPandas[39;00m
[0;32m----> 2[0m world_map [38;5;241m=[39m geopandas[38;5;241m.[39mread_file([43mgeopandas[49m[38;5;241;43m.[39;49m[43mdatasets[49m[38;5;241;43m.[39;49m[43mget_path[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mnaturalearth_lowres[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[1;32m      4[0m [38;5;66;03m# Set up world map plot[39;00m
[1;32m      5[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m15[39m, [38;5;241m10[39m))

File [0;32m~/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/geopandas/datasets/__init__.py:18[0m, in [0;36mget_path[0;34m(dataset)[0m
[1;32m     12[0m error_msg [38;5;241m=[39m (
[1;32m     13[0m     [38;5;124m"[39m[38;5;124mThe geopandas.dataset has been deprecated and was removed in GeoPandas [39m[38;5;124m"[39m
[1;32m     14[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124m1.0. You can get the original [39m[38;5;124m'[39m[38;5;132;01m{[39;00mdataset[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m data from [39m[38;5;124m"[39m
[1;32m     15[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mne_message[38;5;250m [39m[38;5;28;01mif[39;00m[38;5;250m [39m[38;5;124m'[39m[38;5;124mnatural[39m[38;5;124m'[39m[38;5;250m [39m[38;5;129;01min[39;00m[38;5;250m [39mdataset[38;5;250m [39m[38;5;28;01melse[39;00m[38;5;250m [39mnybb_message[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     16[0m )
[1;32m     17[0m [38;5;28;01mif[39;00m dataset [38;5;129;01min[39;00m _prev_available:
[0;32m---> 18[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(error_msg)
[1;32m     19[0m [38;5;28;01melse[39;00m:
[1;32m     20[0m     error_msg [38;5;241m=[39m (
[1;32m     21[0m         [38;5;124m"[39m[38;5;124mThe geopandas.dataset has been deprecated and [39m[38;5;124m"[39m
[1;32m     22[0m         [38;5;124m"[39m[38;5;124mwas removed in GeoPandas 1.0. New sample datasets are now available [39m[38;5;124m"[39m
[1;32m     23[0m         [38;5;124m"[39m[38;5;124min the geodatasets package (https://geodatasets.readthedocs.io/en/latest/)[39m[38;5;124m"[39m
[1;32m     24[0m     )

[0;31mAttributeError[0m: The geopandas.dataset has been deprecated and was removed in GeoPandas 1.0. You can get the original 'naturalearth_lowres' data from https://www.naturalearthdata.com/downloads/110m-cultural-vectors/.

